name: infra deploy

on:
  push:
  pull_request:
  workflow_dispatch:

env:
  ARM_CLIENT_ID: "47fc8819-b636-454c-90e8-28d76d3dc7f5"
  ARM_CLIENT_SECRET: "CeP8Q~ps3154TF76WeS3a5xnHkdGThMVfIowIcWp"
  ARM_SUBSCRIPTION_ID: "85836618-910f-4674-bdec-de824f906976"
  ARM_TENANT_ID: "a346579b-6756-4449-9aec-b49aa7c08b1b"

jobs:
  deploy:
    name: deploy
    runs-on: ubuntu-latest

    steps:
      - name: checkout git repo
        uses: actions/checkout@v2

      - uses: hashicorp/setup-terraform@v2
        name: setup terraform

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan

      - name: Terraform Apply
        run: terraform apply -auto-approve

